{
 "title": "aranet4",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(aranet4_co2_ppm,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CO2",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "expr": "max(aranet4_co2_ppm{instance=~\"$instance\"}) by (instance,device_addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "max(aranet4_temperature_celsius{instance=~\"$instance\"}) by (instance,device_addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "expr": "max(aranet4_pressure_hpa{instance=~\"$instance\"}) by (instance,device_addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(aranet4_humidity_percent{instance=~\"$instance\"}) by (instance,device_addr)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(aranet4_battery_level_percent{instance=~\"$instance\"}) by (instance,device_addr)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}